// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHyqgzT8XwWrwuxRLzCoko8HgDFf9vGqo',
    appId: '1:732929338018:web:520f9f807c7b3b49f985fb',
    messagingSenderId: '732929338018',
    projectId: 'connectx-b70d6',
    authDomain: 'connectx-b70d6.firebaseapp.com',
    databaseURL: 'https://connectx-b70d6-default-rtdb.firebaseio.com',
    storageBucket: 'connectx-b70d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyqgzT8XwWrwuxRLzCoko8HgDFf9vGqo',
    appId: '1:732929338018:android:520f9f807c7b3b49f985fb',
    messagingSenderId: '732929338018',
    projectId: 'connectx-b70d6',
    databaseURL: 'https://connectx-b70d6-default-rtdb.firebaseio.com',
    storageBucket: 'connectx-b70d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHyqgzT8XwWrwuxRLzCoko8HgDFf9vGqo',
    appId: '1:732929338018:ios:520f9f807c7b3b49f985fb',
    messagingSenderId: '732929338018',
    projectId: 'connectx-b70d6',
    databaseURL: 'https://connectx-b70d6-default-rtdb.firebaseio.com',
    storageBucket: 'connectx-b70d6.firebasestorage.app',
    iosBundleId: 'com.example.connectx',
  );
}
